Name:           ros-jade-plotjuggler
Version:        1.0.5
Release:        0%{?dist}
Summary:        ROS plotjuggler package

Group:          Development/Libraries
License:        LGPLv3
URL:            https://github.com/facontidavide/PlotJuggler
Source0:        %{name}-%{version}.tar.gz

Requires:       binutils-devel
Requires:       qt5-qtbase-devel
Requires:       qt5-qtsvg-devel
Requires:       ros-jade-ros-type-introspection
Requires:       ros-jade-rosbag
Requires:       ros-jade-rosbag-storage
Requires:       ros-jade-roscpp
Requires:       ros-jade-roscpp-serialization
Requires:       ros-jade-rostime
Requires:       ros-jade-topic-tools
BuildRequires:  binutils-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-ros-type-introspection
BuildRequires:  ros-jade-rosbag
BuildRequires:  ros-jade-rosbag-storage
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roscpp-serialization
BuildRequires:  ros-jade-rostime
BuildRequires:  ros-jade-topic-tools

%description
PlotJuggler: juggle with data

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sun May 07 2017 Davide Faconti <davide.faconti@gmail.com> - 1.0.5-0
- Autogenerated by Bloom

* Fri Apr 28 2017 Davide Faconti <davide.faconti@gmail.com> - 1.0.3-0
- Autogenerated by Bloom

* Sat Apr 22 2017 Davide Faconti <davide.faconti@gmail.com> - 1.0.0-1
- Autogenerated by Bloom

* Sat Apr 22 2017 Davide Faconti <davide.faconti@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

* Fri Apr 21 2017 Davide Faconti <davide.faconti@gmail.com> - 0.18.0-0
- Autogenerated by Bloom

* Sun Apr 02 2017 Davide Faconti <davide.faconti@gmail.com> - 0.17.0-0
- Autogenerated by Bloom

* Wed Mar 22 2017 Davide Faconti <davide.faconti@gmail.com> - 0.15.3-0
- Autogenerated by Bloom

* Wed Mar 22 2017 Davide Faconti <davide.faconti@gmail.com> - 0.15.2-0
- Autogenerated by Bloom

* Sun Mar 12 2017 Davide Faconti <davide.faconti@gmail.com> - 0.13.0-0
- Autogenerated by Bloom

* Mon Mar 06 2017 Davide Faconti <davide.faconti@gmail.com> - 0.12.1-0
- Autogenerated by Bloom

* Thu Feb 23 2017 Davide Faconti <davide.faconti@gmail.com> - 0.11.0-0
- Autogenerated by Bloom

* Tue Feb 21 2017 Davide Faconti <davide.faconti@gmail.com> - 0.10.3-0
- Autogenerated by Bloom

* Tue Feb 07 2017 Davide Faconti <davide.faconti@gmail.com> - 0.9.0-0
- Autogenerated by Bloom

