# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import math_pb2 as math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_state.proto',
  package='flr.robot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11robot_state.proto\x12\tflr.robot\x1a\nmath.proto\"\x8b\x02\n\nRobotState\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\x12,\n\x06\x63orpus\x18\x04 \x01(\x0e\x32\x1c.flr.robot.RobotState.Corpus\x12\x1d\n\x03pos\x18\x05 \x01(\x0b\x32\x10.flr.math.Vector\x12\x17\n\x0fjoint_positions\x18\x06 \x03(\x01\"Z\n\x06\x43orpus\x12\r\n\tUNIVERSAL\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\n\n\x06IMAGES\x10\x02\x12\t\n\x05LOCAL\x10\x03\x12\x08\n\x04NEWS\x10\x04\x12\x0c\n\x08PRODUCTS\x10\x05\x12\t\n\x05VIDEO\x10\x06\x62\x06proto3')
  ,
  dependencies=[math__pb2.DESCRIPTOR,])



_ROBOTSTATE_CORPUS = _descriptor.EnumDescriptor(
  name='Corpus',
  full_name='flr.robot.RobotState.Corpus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNIVERSAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEWS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCTS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=222,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_ROBOTSTATE_CORPUS)


_ROBOTSTATE = _descriptor.Descriptor(
  name='RobotState',
  full_name='flr.robot.RobotState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='flr.robot.RobotState.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='flr.robot.RobotState.page_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='flr.robot.RobotState.result_per_page', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corpus', full_name='flr.robot.RobotState.corpus', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='flr.robot.RobotState.pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joint_positions', full_name='flr.robot.RobotState.joint_positions', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTSTATE_CORPUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=312,
)

_ROBOTSTATE.fields_by_name['corpus'].enum_type = _ROBOTSTATE_CORPUS
_ROBOTSTATE.fields_by_name['pos'].message_type = math__pb2._VECTOR
_ROBOTSTATE_CORPUS.containing_type = _ROBOTSTATE
DESCRIPTOR.message_types_by_name['RobotState'] = _ROBOTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotState = _reflection.GeneratedProtocolMessageType('RobotState', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTSTATE,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:flr.robot.RobotState)
  ))
_sym_db.RegisterMessage(RobotState)


# @@protoc_insertion_point(module_scope)
